typography_spectrum: 0.75069
color:
  brandColors:
    - '#ffffff'
    - '#999999'
    - '#646464'
    - '#3f3f3f'
    - '#191919'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.98125
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: John Williams
  email: jfwilliams35@gmail.com
name: B E L O V E D
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: The adventure of being loved by God
purpose: []
