name: Beloved
favicon: null
layout_spectrum: 0
typography_spectrum: 0.75069
title: B E L O V E D
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#999999'
    - '#646464'
    - '#3f3f3f'
    - '#191919'
  brandStrength: 1
  lightness: 1
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
