name: Beloved
favicon: null
layout_spectrum: 0.3933516687247902
typography_spectrum: 0.08550165849737823
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5829838884528726
  lightness: 0.10414208634756505
  saturation: 0.8268590881489217
  rhythmicContrast: 0.2877702722325921
purpose: []
